spring:
  application:
    name: result-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/resultdb
      auto-index-creation: true

  # ActiveMQ Artemis Configuration
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  port: 8084
jwt:
  secret: am9pbmdpcmxhbGFuaW1hbHNob2VibGluZHBhbnRiZWxsY3VycmVudGFkZGl0aW9ud2Fu=
